version: '3.8'

services:
  app:
    image: your_dockerhub_haystacks/myapp:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/chatdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1110
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: chatdb
      MYSQL_ROOT_PASSWORD: 1110
      MYSQL_USER: root
      MYSQL_PASSWORD: 1110
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: